name: First Workflow

on: 
 workflow_dispacth:

jobs:
  job1:
    runs-on: ubuntu-latest
     steps:
      - name: Step one
        run: echo "Log from step one"
      - name: Step two
        run: echo "Logo from step two"
